export const FETCH_EVENT_DETAILS = 'FETCH_EVENT_DETAILS';
export const LOADING_EVENT_DETAIL_SUCCESS = 'LOADING_EVENT_DETAIL_SUCCESS';
export const LOADING_EVENT_DETAIL_FAILURE = 'LOADING_EVENT_DETAIL_FAILURE';
